name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  VERSIONDT: abc
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setVersion.outputs.version }}
    steps:
      - name: setVersion
        run: echo "::set-output name=version::1.0.0.$(date -u +%Y%m%d%H%M%S)"
      - name: readVersion
        run: |
          echo "readVersion v$version"
          echo "readVersion v${{ steps.setVersion.outputs.version }}"
  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo line 1
          echo line 2
      - name: version
        run: echo v${{ needs.version.outputs.version }}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - id: step3
        run: echo "step3  ${{ steps.step2.outputs.test }}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
