name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  VERSIONDT: abc
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: set-version
        run: |
          export V=1.0.0.$(date -u +%Y%m%d%H%M%S)
          echo $V
          echo "v$V"
          echo "::set-output name=version::$V"
  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo line 1
          echo line 2
      - name: version
        run: echo v$VERSION
